### ISSUE TITLE
Kdeinit4 doesn't work with libdbusmenu-qt built with Katie.

### ISSUE THREAD

**Issue by FredBezies** [fluxer/kdelibs#3]
After building libdbusmenu-qt4 with Katie, adding it as a depend for katanalibs, rebuild katana-libs with dbusqt option activated and launching Kdm, session launching doesn't work.

![VirtualBox_endos test_31_01_2020_15_19_47](https://user-images.githubusercontent.com/8571419/73546227-29035700-443d-11ea-86f1-abe7bc037e9a.png)

Here is the log:

```
********************************************************************************
Note that your system uses syslog. All of kdm's internally generated messages
(i.e., not from libraries and external programs/scripts it uses) go to the
daemon.* syslog facility; check your syslog configuration to find out to which
file(s) it is logged. PAM logs messages related to authentication to authpriv.*.
********************************************************************************

pci id for fd 14: 80ee:beef, driver (null)
QFont::fromString: Invalid description 'Serif,20,-1,5,50,0,0,0,0,0'
QFont::fromString: Invalid description 'Sans Serif,10,-1,5,50,0,0,0,0,0'
QFont::fromString: Invalid description 'Sans Serif,10,-1,5,75,0,0,0,0,0'
klauncher(684) main: No DBUS session-bus found. Check if you have started the DBUS server. 
kdeinit4: Communication error with launcher. Exiting!
kdmgreet(678)/kdecore (K*TimeZone*): KSystemTimeZones: ktimezoned initialize() D-Bus call failed:  "Not connected to D-Bus server" 
```

Looks like katie port is not working well.

**Comment by fluxer** [comment]
`qdbus` binary name is hardcoded into [startkde](https://github.com/fluxer/kde-workspace/blob/master/startkde.cmake#L23) script and Katie's binaries path defaults to standard path (e.g. /usr/bin) rather than custom path which requries `PATH` environment variable override for some applications to find the binaries.

As noted in the [README](https://github.com/fluxer/katie/blob/master/README#L87) of Katie, mixing applications can cause problems and that seems to be your case. `startkde` is starting `qdbus` which is not from Katie.

Either edit `startkde` on your system or better patch it when packaging kde-workspace as is done for [applications.menu](https://github.com/fluxer/katana/blob/master/packaging/archlinux/katanalibs/kde-applications-menu.patch) file.

**Comment by FredBezies** [comment]
Well, if you modified qdbus with qdbus-katie, it launches. Will try to do another build from scratch asap.

I did not think I mixed libs within my build process... 

Looks like another building process will be needed. I'll try to get some time to do this next week.

**Comment by fluxer** [comment]
To ensure is nothing linked to Qt libraries use the files list output of `pacman` and pipe it to `ldd`, `grep` for libQt. Something like:
`ldd $(pacman -Ql katanalibs) 2>&1 | grep libQt`

If there is anything related to libQt in the output you will have to dive into it and find what exactly is linked to Qt libraries, if at all.

Cheers!

**Comment by FredBezies** [comment]
Well...

```
[fred@fredo-pc ~]$ ldd $(pacman -Ql katanalibs) 2>&1 | grep libQt
[fred@fredo-pc ~]$ 
```

Nothing at all :(

Looks like I'll have to patch startkde... I'll do this later. I don't have time to do that now.

**Comment by fluxer** [comment]
Check not only katanalibs but also the other packages aswell, including QCA, Poppler, etc.

**Comment by FredBezies** [comment]
Here are some more results:

```
[fred@fredo-pc ~]$ ldd $(pacman -Ql katana-baseapps) 2>&1 | grep libQt
[fred@fredo-pc ~]$ ldd $(pacman -Ql katana-workspace) 2>&1 | grep libQt
[fred@fredo-pc ~]$ ldd $(pacman -Ql katana-extraapps) 2>&1 | grep libQt
[fred@fredo-pc ~]$ ldd $(pacman -Ql qimageblitz) 2>&1 | grep libQt
[fred@fredo-pc ~]$ ldd $(pacman -Ql qca-qt4) 2>&1 | grep libQt
[fred@fredo-pc ~]$ ldd $(pacman -Ql libmygpo-qt4) 2>&1 | grep libQt
[fred@fredo-pc ~]$ ldd $(pacman -Ql strigi) 2>&1 | grep libQt
[fred@fredo-pc ~]$ ldd $(pacman -Ql katie-git) 2>&1 | grep libQt
[fred@fredo-pc ~]$ ldd $(pacman -Ql liblastfm-qt4) 2>&1 | grep libQt
```

**Comment by fluxer** [comment]
Good idea, however if the VM has either local installation of Qt or Qt packages are pulled as dependency of other package when you install the dependencies required to build Katana there still may be issues.

**Comment by FredBezies** [comment]
Tried to build in a clean chroot, same problem. Looks like it will need some more work on katie version to be OK.

It was interesting to try in a clean chroot :)

**Comment by fluxer** [comment]
It does :smile:, that's why it is still not default in the Arch package files. Once I start packaging Katana for Debian which I plan on doing soon, probably after the next release candidate of Katie, I will see see for myself.

Before that happens tho, I have to update the software with Katie support. A new release for Katana has to be made prior to that as some changes to Katana itself may be required but [testing](https://github.com/fluxer/katana/issues/2) has to be done first.

There is a lot to be done basicly but it will happen, eventually.

Cheers!
